/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coursescheduler.views.pages.subpages;
import coursescheduler.views.pages.containers.PageControl;
import coursescheduler.views.pages.containers.dummyCourse;
import coursescheduler.views.pages.containers.dummyUser;
import java.awt.Font;


/**
 *
 * @author evilc
 */
public class AddCourseDepartmentChairPage extends javax.swing.JPanel {
    PageControl control;
    String page = "ADD_COURSE_DEPARTMENT_CHAIR";
    inputSingleCourseDataTable editor;
    boolean validCollege = false;
    boolean validID = false;
    boolean validName = false;
    boolean validProfessor = false;
    boolean validRoom = false;
    boolean validTimes = false;
    boolean validDays = false;
    boolean validSeats = false;
    boolean allInputsValid = false;
    int textSize = 12;
    
    
    public void setPageSettingsControl(PageControl input)
    {
        control = input;
    }
    
    public void setTextSize(int input)
    {
        textSize = input;
    }
    
    public int getTextSize()
    {
        return textSize;
    }
    
    
    public void updateTextSize()
    {
        this.setTextSize(textSize);
        int size1 = jLabel1.getFont().getSize();
        int difference1 = size1 - textSize;
        Font newFont1 = new Font("Tahoma", Font.PLAIN,  textSize);
        Font newFont2 = new Font("Tahoma", Font.PLAIN,  (textSize + difference1));
        jLabel1.setFont(newFont2); //Add Course
        jLabel2.setFont(newFont1); //College:
        jLabel3.setFont(newFont1); //ID:
        jLabel4.setFont(newFont1); //Name:
        jLabel5.setFont(newFont1); //Professor:
        jLabel6.setFont(newFont1); //Room:
        jLabel7.setFont(newFont1); //Times:
        jLabel8.setFont(newFont1); //Days:
        jLabel9.setFont(newFont1); //Seats:
        selectCollegeComboBox.setFont(newFont1);
        selectRoomComboBox.setFont(newFont1);
        selectTimesComboBox.setFont(newFont1);
        selectDaysComboBox.setFont(newFont1);
        submitButton.setFont(newFont1);
        idInput.setFont(newFont1);
        nameInput.setFont(newFont1);
        professorInput.setFont(newFont1);
        seatsInput.setFont(newFont1);
    }
    
    
    
    public String returnPage()
    {
        return page;
    }
    
    public AddCourseDepartmentChairPage() 
    {
        initComponents();
        editor = new inputSingleCourseDataTable();;
    }
    

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        professorInput = new javax.swing.JTextField();
        idInput = new javax.swing.JTextField();
        selectTimesComboBox = new javax.swing.JComboBox<>();
        selectDaysComboBox = new javax.swing.JComboBox<>();
        selectRoomComboBox = new javax.swing.JComboBox<>();
        addCourseErrorDisplay1 = new javax.swing.JLabel();
        addCourseError_College = new javax.swing.JLabel();
        addCourseError_Professor = new javax.swing.JLabel();
        addCourseError_ID = new javax.swing.JLabel();
        addCourseError_Name = new javax.swing.JLabel();
        addCourseError_Days = new javax.swing.JLabel();
        addCourseError_Room = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        seatsInput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        addCourseError_Seats = new javax.swing.JLabel();
        addCourseError_Times = new javax.swing.JLabel();
        selectCollegeComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        selectSectionComboBox = new javax.swing.JComboBox<>();
        addCourseError_Section = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Add Course");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("College:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("ID:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Professor:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Room:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Times:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Days:");

        professorInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorInputActionPerformed(evt);
            }
        });

        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });

        selectTimesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Times", "9:30am - 11:00am", "11:40am - 12:15pm", "3:30am - 5:00am" }));
        selectTimesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTimesComboBoxActionPerformed(evt);
            }
        });

        selectDaysComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Days", "M, W, F", "M, W", "T, TH" }));
        selectDaysComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDaysComboBoxActionPerformed(evt);
            }
        });

        selectRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Room", "1A", "2B", "3C" }));
        selectRoomComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectRoomComboBoxActionPerformed(evt);
            }
        });

        addCourseErrorDisplay1.setForeground(java.awt.Color.red);

        addCourseError_College.setForeground(java.awt.Color.red);

        addCourseError_Professor.setForeground(java.awt.Color.red);

        addCourseError_ID.setForeground(java.awt.Color.red);

        addCourseError_Name.setForeground(java.awt.Color.red);

        addCourseError_Days.setForeground(java.awt.Color.red);

        addCourseError_Room.setForeground(java.awt.Color.red);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Seats:");

        seatsInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatsInputActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Name:");

        nameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameInputActionPerformed(evt);
            }
        });

        addCourseError_Seats.setForeground(java.awt.Color.red);

        addCourseError_Times.setForeground(java.awt.Color.red);

        selectCollegeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select College", "Science", "History", "Engineering" }));
        selectCollegeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCollegeComboBoxActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Section");

        selectSectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Section", "1", "2", "3" }));
        selectSectionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSectionComboBoxActionPerformed(evt);
            }
        });

        addCourseError_Section.setForeground(java.awt.Color.red);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectSectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(submitButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameInput)
                                    .addComponent(professorInput)
                                    .addComponent(idInput)
                                    .addComponent(selectTimesComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selectDaysComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selectRoomComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addCourseErrorDisplay1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(seatsInput)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(selectCollegeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addCourseError_College, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addCourseError_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addCourseError_ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addCourseError_Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addCourseError_Room, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addCourseError_Days, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCourseError_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCourseError_Times, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCourseError_Section, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(addCourseErrorDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(addCourseError_College, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectCollegeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(addCourseError_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(addCourseError_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(selectSectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(addCourseError_Professor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(professorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(selectRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCourseError_Room, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submitButton)
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(addCourseError_Times, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectTimesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(addCourseError_Days, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectDaysComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(addCourseError_Seats, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seatsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCourseError_Section, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seatsInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatsInputActionPerformed
        // Seats text input
    }//GEN-LAST:event_seatsInputActionPerformed

    
    private void selectRoomComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectRoomComboBoxActionPerformed
        // Combo box for selecting the room
    }//GEN-LAST:event_selectRoomComboBoxActionPerformed

    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // Submit button
       dummyCourse temp = getCourse();
       if (temp != null && allInputsValid)
       {
           control.addCourseDepartmentChair(temp);
           selectCollegeComboBox.setSelectedItem("Select College");
           selectRoomComboBox.setSelectedItem("Select Room");
           selectTimesComboBox.setSelectedItem("Select Times");;
           selectDaysComboBox.setSelectedItem("Select Days");
           idInput.setText("");
           nameInput.setText("");
           professorInput.setText("");
           seatsInput.setText("");
       }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void selectCollegeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCollegeComboBoxActionPerformed
        // College combo box selection
        
    }//GEN-LAST:event_selectCollegeComboBoxActionPerformed

    
    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        //ID text input
 
    }//GEN-LAST:event_idInputActionPerformed

    private void nameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameInputActionPerformed
        //Name text input
    }//GEN-LAST:event_nameInputActionPerformed

    private void professorInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorInputActionPerformed
        //Professor text input
    }//GEN-LAST:event_professorInputActionPerformed

    private void selectTimesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTimesComboBoxActionPerformed
        //Combo box for selecting the time
    }//GEN-LAST:event_selectTimesComboBoxActionPerformed

    private void selectDaysComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDaysComboBoxActionPerformed
        //Combo box for selecting the room
    }//GEN-LAST:event_selectDaysComboBoxActionPerformed

    private void selectSectionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSectionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectSectionComboBoxActionPerformed
    
    public void checkSeats()
    {
        String Seats_string = seatsInput.getText();
        int seats;
        if (!Seats_string.equals(""))
        {
             try
            {
                seats = Integer.parseInt(Seats_string.trim());
                addCourseError_Seats.setText("");
                validSeats = true;
            }
            catch (NumberFormatException nfe)
            {
                addCourseError_Seats.setText("*");
                validSeats = false;
            }  
        }
        else
        {
            addCourseError_Seats.setText("*");
            validSeats = false;
        }
    }
    
    public void checkRoom()
    {
        String Room = (String) selectRoomComboBox.getSelectedItem();
        if (!(Room.equals("")) && !(Room.equals("Select Room")))
        {
            validRoom = true;
            addCourseError_Room.setText("");
        }
        else
        {
            addCourseError_Room.setText("*");
            validRoom = false;
        }
    }
    
    public void checkTimes()
    {
        String Times = (String) selectTimesComboBox.getSelectedItem();
        if ((Times.equals("")) || (Times.equals("Select Times")))
        {
            validTimes = false;
            addCourseError_Times.setText("*");
        }
        else
        {
            addCourseError_Times.setText("");
            validTimes = true;
        }
    }
    
    public void checkDays()
    {
        String Days = (String) selectDaysComboBox.getSelectedItem();
        if (!(Days.equals("")) && !(Days.equals("Select Days")))
        {
            validDays = true;
            addCourseError_Days.setText("");
        }
        else
        {
            addCourseError_Days.setText("*");
            validDays = false;
        }
    }
    
    public void checkCollege()
    {
        String College = (String) selectCollegeComboBox.getSelectedItem();
        if ((College.equals("") || (College.equals("Select College"))))
        {
            addCourseError_College.setText("*");
            validCollege = false;
        }
        else
        {
            validCollege = true;
            addCourseError_College.setText("");
        }
    }
    
    public void checkName()
    {
        String Name = nameInput.getText();
        if (!control.checkSameName(Name))
        {
            if (!(Name.equals("")))
            {
            validName = true;
            addCourseError_Name.setText("");
            }
            else
            {
                validName = false;
                addCourseError_Name.setText("*");
            }
        }
        else
        {
            addCourseError_Name.setText("*");
            validName = false;
        }
       
    }
    
    public void checkID()
    {
        String ID_string = idInput.getText();
        int ID;
        if (!ID_string.equals(""))
        {
            try
            {
                ID = Integer.parseInt(ID_string.trim());
                if (!control.checkSameID(ID))
                {
                    addCourseError_ID.setText("");
                    validID = true;
                }
                else
                {
                    addCourseError_ID.setText("*");
                    validID = false;
                }
            }
            catch (NumberFormatException nfe)
            {
                addCourseError_ID.setText("*");
                validID = false;
            }  
        }
        else
        {
            addCourseError_ID.setText("*");
            validID = false;
        }
    }
    
    public void checkProfessor()
    {
        String Professor = professorInput.getText();
        if (!(Professor.equals("")))
        {
            validProfessor = true;
            addCourseError_Professor.setText("");
        }
        else
        {
            validProfessor = false;
            addCourseError_Professor.setText("*");
        }
    }
  
    public void checkAllInputs()
    {   
       checkCollege();
       checkID();
       checkName();
       checkProfessor();
       checkRoom();
       checkTimes();
       checkDays();
       checkSeats();
       
       if (validCollege && validID && validName && validProfessor && validTimes && validDays && validSeats)
       {
           allInputsValid = true;
           //System.out.println("CORRECT");
       }
       else
       {
           allInputsValid = false;
           
       }
    }

    public int getSeats()
    {
        int seats = -1;
        checkSeats();
        if (validSeats)
        {
             String Seats_string = seatsInput.getText();
             seats = Integer.parseInt(Seats_string.trim());
        }
        return seats;
    }
    
    public int getID()
    {
        int ID = -1;
        checkID();
        if (validID)
        {
             String ID_string = idInput.getText();
             ID = Integer.parseInt(ID_string.trim());
        }
        return ID;
    }
    
    public String getCollege()
    {
        String college = "INCORRECT_VALUE_SELECTED";
        checkCollege();
        if (validCollege)
        {
            college = (String) selectCollegeComboBox.getSelectedItem();
        }
        return college;
    }
    
    public String getRoom()
    {
        String room = "INCORRECT_VALUE_SELECTED";
        checkRoom();
        if (validRoom)
        {
            room = (String) selectRoomComboBox.getSelectedItem();
        }
        return room;
    }
    
    public String getTimes()
    {
        String times = "INCORRECT_VALUE_SELECTED";
        checkTimes();
        if (validTimes)
        {
            times = (String) selectTimesComboBox.getSelectedItem();
        }
        return times;
    }
    
    public String getDays()
    {
        String days= "INCORRECT_VALUE_SELECTED";
        checkDays();
        if (validDays)
        {
            days = (String) selectDaysComboBox.getSelectedItem();
        }
        return days;
    }
    
    public String getProfessor()
    {
       String professor = "INCORRECT_INPUT";
       checkProfessor();
       if(validProfessor)
       {
           professor = professorInput.getText();
       }
       return professor;
    }
    
    public String getName()
    {
       String name = "INCORRECT_INPUT";
       checkName();
       if(validName)
       {
           name = nameInput.getText();
       }
       return name;
    }
    
    dummyCourse getCourse()
    {
        checkAllInputs();
        dummyCourse temp = null;
        if (allInputsValid)
        {
            temp = new dummyCourse();
            temp.setCollege(getCollege());
            temp.setID(getID());
            temp.setName(getName());
            temp.setProfessor(getProfessor());
            temp.setTimes(getTimes());
            temp.setDays(getDays());
            temp.setRoom(getRoom());
            temp.setSeats(getSeats());
        }
        return temp;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addCourseErrorDisplay1;
    private javax.swing.JLabel addCourseError_College;
    private javax.swing.JLabel addCourseError_Days;
    private javax.swing.JLabel addCourseError_ID;
    private javax.swing.JLabel addCourseError_Name;
    private javax.swing.JLabel addCourseError_Professor;
    private javax.swing.JLabel addCourseError_Room;
    private javax.swing.JLabel addCourseError_Seats;
    private javax.swing.JLabel addCourseError_Section;
    private javax.swing.JLabel addCourseError_Times;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameInput;
    private javax.swing.JTextField professorInput;
    private javax.swing.JTextField seatsInput;
    private javax.swing.JComboBox<String> selectCollegeComboBox;
    private javax.swing.JComboBox<String> selectDaysComboBox;
    private javax.swing.JComboBox<String> selectRoomComboBox;
    private javax.swing.JComboBox<String> selectSectionComboBox;
    private javax.swing.JComboBox<String> selectTimesComboBox;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
