package coursescheduler;
import coursescheduler.managers.PanelController;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author evilc
 */
public class AddCoursePageFaculty extends javax.swing.JPanel {
    String page = "ADD_COURSE_FACULTY";
    PanelController controller;
    inputSingleCourseDataTable editor;
    boolean validSelection = false;
    

    public void setController(PanelController input)
    {
        controller = input;
    }
    
    public String returnPage()
    {
        return page;
    }
    public AddCoursePageFaculty() {
        initComponents();
        editor = new inputSingleCourseDataTable();
    }
    
    public void setTable(Object[] input)
    {
        Table1.setModel(editor.setTableData(input, (DefaultTableModel) Table1.getModel()));
    }
    
    public void setCollege(String input)
    {
        Table1.setModel(editor.setCollege(input, (DefaultTableModel) Table1.getModel()));
    }
    
    public void setID(int input)
    {
        Table1.setModel(editor.setID(input, (DefaultTableModel) Table1.getModel()));
    }
    
    public void setName(String input)
    {
        Table1.setModel(editor.setName(input, (DefaultTableModel) Table1.getModel()));
    }
    
    public void setProfessor(String input)
    {
        Table1.setModel(editor.setProfessor(input, (DefaultTableModel) Table1.getModel()));
    }
    
    public void setRoom(String input)
    {
        Table1.setModel(editor.setRoom(input, (DefaultTableModel) Table1.getModel()));
    }
    
    public void setTimes(String input)
    {
        Table1.setModel(editor.setTimes(input, (DefaultTableModel) Table1.getModel()));
    }
    
    public void setDays(String input)
    {
        Table1.setModel(editor.setDays(input, (DefaultTableModel) Table1.getModel()));
    }
    
    public void setSeats(int input)
    {
        Table1.setModel(editor.setSeats(input, (DefaultTableModel) Table1.getModel()));
    }
    
    void checkSelection()
    {
        String course = (String) allCoursesCombo.getSelectedItem();
        if (!(course.equals("") && !(course.equals("Select Course"))))
        {
            validSelection = true;
        }
        else
        {
            validSelection = false;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allCoursesCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        addCourseSubmitButton = new javax.swing.JButton();
        addCourseCancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        allCoursesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Course" }));
        allCoursesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCoursesComboActionPerformed(evt);
            }
        });

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"College:", null},
                {"ID:", null},
                {"Name:", null},
                {"Professor:", null},
                {"Room(s):", null},
                {"Times:", null},
                {"Days:", null},
                {"Seats:", null}
            },
            new String [] {
                "Course Info", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table1);

        addCourseSubmitButton.setText("Submit");
        addCourseSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseSubmitButtonActionPerformed(evt);
            }
        });

        addCourseCancelButton.setText("Cancel");
        addCourseCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseCancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Add Course");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(allCoursesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addCourseCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addCourseSubmitButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addComponent(allCoursesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCourseSubmitButton)
                    .addComponent(addCourseCancelButton))
                .addGap(4, 4, 4))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void allCoursesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCoursesComboActionPerformed
        // Combo box (when the user selects something from the combo box)
        
    }//GEN-LAST:event_allCoursesComboActionPerformed

    private void addCourseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseSubmitButtonActionPerformed
        // Submit button
        
    }//GEN-LAST:event_addCourseSubmitButtonActionPerformed

    private void addCourseCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseCancelButtonActionPerformed
        // Cancel button
        
    }//GEN-LAST:event_addCourseCancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JButton addCourseCancelButton;
    private javax.swing.JButton addCourseSubmitButton;
    private javax.swing.JComboBox<String> allCoursesCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
